#!/bin/bash
# Configure wmii
wmiiscript=wmiirc # For wmii.sh
. wmii.sh


# Configuration Variables
MODKEY=Mod4
UP=q
DOWN=a
LEFT=z
RIGHT=x

# Bars
noticetimeout=5
noticebar=/rbar/!notice

soundbar=/rbar/sound

#Bar at top
wmiir xwrite /ctl bar on top 

# Colors tuples: "<text> <background> <border>"
export WMII_NORMCOLORS='#000000 #c1c48b #81654f'
export WMII_FOCUSCOLORS='#000000 #81654f #000000'

export WMII_BACKGROUND='#333333'
export WMII_FONT='xft:Sans-10'

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
export WMII_TERM="gnome-terminal --disable-factory -e \"bash -il\""

# Ask about MODKEY on first run
    if ! test -d "${WMII_CONFPATH%%:*}"; then
        mkdir "${WMII_CONFPATH%%:*}"
        res=$(wihack -type DIALOG xmessage -nearmouse -buttons Windows,Alt -print -fn $WMII_FONT \
              "Welcome to wmii,$wi_newline$wi_newline" \
              "Most of wmii's default key bindings make use of the$wi_newline" \
              "Windows key, or equivalent. For keyboards lacking such$wi_newline" \
              "a key, many users change this to the Alt key.$wi_newline$wi_newline" \
              "Which would you prefer?")
        [ "$res" = "Alt" ] && MODKEY=Mod1
        echo "MODKEY=$MODKEY" >"${WMII_CONFPATH%%:*}/wmiirc_local"
        chmod +x "${WMII_CONFPATH%%:*}/wmiirc_local"
    fi

# Menu history
hist="${WMII_CONFPATH%%:*}/history"
histnum=5000

# Column Rules
wmiir write /colrules <<!
    /gimp/ -> 15+65+20
    /.*/ -> 62+38 # Golden Ratio
!

TOP_TERMINAL_NAME="TOP"

# Tagging Rules
wmiir write /rules <<!
    # Apps with system tray icons like to their main windows
    # Give them permission.
    /^Pidgin:/ allow=+activate

    # MPlayer and VLC don't float by default, but should.
    /MPlayer|VLC/ floating=on

    # ROX puts all of its windows in the same group, so they open
    # with the same tags.  Disable grouping for ROX Filer.
    /^ROX-Filer:/ group=0

    /.*Mozilla Firefox$/ tags=2
    /.*Chromium$/ tags=2

    /.*/ tags=sel
!

# Status Bar Info
status() {
	percent=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 |grep perce | grep -o "[0-9]*")
	status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 |grep state |grep -o [A-Za-z-]*$)
	last_time=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep time | grep -o -E "[0-9].*")
	BAT="Battery: $percent%($status) $last_time"
	echo -n label $BAT '|' $(date)
}

top_terminal() {
	gnome-terminal --disable-factory -t $TOP_TERMINAL_NAME -e "top -i -d 1" &

}

health_saver_service() {
	while true; do
		sleep 48m
		notify-send "Передохни"
	done
}


health_saver() {
	kill `cat $(wmiir namespace)/.healther_pid` > /dev/null 2>&1
	{ health_saver_service; }&
	echo -n $! > $(wmiir namespace)/.healther_pid
}

HELPER_FIFO_IN=/tmp/.wmii-helper-in

# Generic overridable startup details
startup() { 
	top_terminal &
	xscreensaver -nosplash &
	dunst -to 0 -lto 0 -nto 0 -cto 0 &
	cd /home/userr/.wmii
	java -jar wmii-helper.jar &> log.txt & 
	cd ~
	gxneur &
	#wicd-gtk -t &
	blueman-applet &
	/usr/bin/python /usr/bin/mintupdate-launcher &
	witray & 
	
}

wi_runconf -s wmiirc_local

echo colors $WMII_NORMCOLORS | wmiir create $soundbar
echo colors $WMII_NORMCOLORS | wmiir create $noticebar


# Event processing
wi_events <<'!'
# Events
Event CreateTag
	echo colors "$WMII_NORMCOLORS$wi_newline" label "$@" | wmiir create "/lbar/$@"
Event DestroyTag
	wmiir remove "/lbar/$@"
Event FocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_FOCUSCOLORS"
Event UnfocusTag
	wmiir xwrite "/lbar/$@" colors "$WMII_NORMCOLORS"
Event UrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "*$@"
Event NotUrgentTag
	shift
	wmiir xwrite "/lbar/$@" label "$@"
Event LeftBarClick LeftBarDND
	shift
	wmiir xwrite /ctl view "$@"
Event Unresponsive
	{
		client=$1; shift
		msg="The following client is not responding. What would you like to do?$wi_newline"
		resp=$(wihack -transient $client \
			      xmessage -nearmouse -buttons Kill,Wait -print \
			      -fn "${WMII_FONT%%,*}" "$msg $(wmiir read /client/sel/label)")
		if [ "$resp" = Kill ]; then
			wmiir xwrite /client/$client/ctl slay &
		fi
	}&
Event Notice
	wmiir xwrite $noticebar "label $wi_arg"
	kill `cat $(wmiir namespace)/.notice_pid` 2>/dev/null # Let's hope this isn't reused...
	{ sleep $noticetimeout; wmiir xwrite $noticebar 'label '; }&
	echo -n $! > $(wmiir namespace)/.notice_pid

# Menus
Menu Client-3-Kill
	wmiir xwrite /client/$1/ctl kill
Menu Client-3-Delete
	wmiir xwrite /client/$1/ctl slay
Menu Client-3-Fullscreen
	wmiir xwrite /client/$1/ctl Fullscreen on
Event ClientMouseDown
	wi_fnmenu Client $2 $1 &

Menu LBar-3-Delete
	tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
	for c in $clients; do
		if [ "$tag" = "$(wmiir read /client/$c/tags)" ]
		then wmiir xwrite /client/$c/ctl kill
		else wmiir xwrite /client/$c/ctl tags -$tag
		fi
		[ "$tag" = "$(wi_seltag)" ] &&
			wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
	done
Event LeftBarMouseDown
	wi_fnmenu LBar "$@" &

# Actions
Action showkeys
	echo "$KeysHelp" | xmessage -file - -fn ${WMII_FONT%%,*}
Action quit
	wmiir xwrite /ctl quit
Action exec
	wmiir xwrite /ctl exec "$@"
Action rehash
	wi_proglist $PATH >$progsfile
Action status
	set +xv
	if wmiir remove /rbar/status 2>/dev/null; then
		sleep 2
	fi
	echo colors "$WMII_NORMCOLORS" | wmiir create /rbar/status
	while status | wmiir write /rbar/status; do
		sleep 1
	done

# Key Bindings
KeyGroup Moving around
Key $MODKEY-$LEFT   # Select the client to the left
	wmiir xwrite /tag/sel/ctl select left
Key $MODKEY-$RIGHT  # Select the client to the right
	wmiir xwrite /tag/sel/ctl select right
Key $MODKEY-$UP     # Select the client above
	wmiir xwrite /tag/sel/ctl select up
Key $MODKEY-$DOWN   # Select the client below
	wmiir xwrite /tag/sel/ctl select down
Key $MODKEY-Tab   # Select the client below
	wmiir xwrite /tag/sel/ctl select down

Key $MODKEY-space   # Toggle between floating and managed layers
	wmiir xwrite /tag/sel/ctl select toggle

KeyGroup Moving through stacks
Key $MODKEY-Control-$UP    # Select the stack above
	wmiir xwrite /tag/sel/ctl select up stack
Key $MODKEY-Control-$DOWN  # Select the stack below
	wmiir xwrite /tag/sel/ctl select down stack

KeyGroup Moving clients around
Key $MODKEY-Shift-$LEFT   # Move selected client to the left
	wmiir xwrite /tag/sel/ctl send sel left
Key $MODKEY-Shift-$RIGHT  # Move selected client to the right
	wmiir xwrite /tag/sel/ctl send sel right
Key $MODKEY-Shift-$UP     # Move selected client up
	wmiir xwrite /tag/sel/ctl send sel up
Key $MODKEY-Shift-$DOWN   # Move selected client down
	wmiir xwrite /tag/sel/ctl send sel down

Key $MODKEY-Shift-space   # Toggle selected client between floating and managed layers
	wmiir xwrite /tag/sel/ctl send sel toggle

KeyGroup Client actions
Key $MODKEY-f # Toggle selected client's fullsceen state
	wmiir xwrite /client/sel/ctl Fullscreen toggle
Key Mod3-e # Close client
	wmiir xwrite /client/sel/ctl kill

KeyGroup Changing column modes
Key $MODKEY-d # Set column to default mode
	wmiir xwrite /tag/sel/ctl colmode sel default-max
Key $MODKEY-s # Set column to stack mode
	wmiir xwrite /tag/sel/ctl colmode sel stack-max
Key $MODKEY-m # Set column to max mode
	wmiir xwrite /tag/sel/ctl colmode sel stack+max

KeyGroup Running programs
Key $MODKEY-y      # Open wmii actions menu
	action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &
Key $MODKEY-r      # Open program menu  eval wmiir setsid "$(wimenu -h "${hist}.progs" -n $histnum <$progsfile)" &
	eval wmiir setsid "$(wimenu -h "${hist}.progs" -n $histnum <$progsfile)" &

Key $MODKEY-Return # Launch a terminal eval wmiir setsid $WMII_TERM &
	eval wmiir setsid $WMII_TERM &

# KeyGroup Other
# Key $MODKEY-Control-t # Toggle all other key bindings
# 	case $(wmiir read /keys | wc -l | tr -d ' \t\n') in
# 	0|1)
# 		echo -n "$Keys" | wmiir write /keys
# 		wmiir xwrite /ctl grabmod $MODKEY;;
# 	*)
# 		wmiir xwrite /keys $MODKEY-Control-t
# 		wmiir xwrite /ctl grabmod Mod3;;
# 	esac

KeyGroup Tag actions
Key $MODKEY-t       # Change to another tag
	wmiir xwrite /ctl view $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-Shift-t # Retag the selected client
	# Assumes left-to-right order of evaluation
	wmiir xwrite /client/$(wi_selclient)/ctl tags $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
Key $MODKEY-e	    # Move to the next tag
	wmiir xwrite /ctl view $(wi_tags | wi_nexttag)
Key $MODKEY-w	    # Move to the previous tag
	wmiir xwrite /ctl view $(wi_tags | sort -r | wi_nexttag)


KeyGroup Sound control
Key XF86AudioMute
	amixer -D pulse set Master toggle
	wmiir xwrite /event Notice "Sound: $(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')($(amixer sget Master | awk -F"[][]" '/dB/ { print $6 }'))"
Key XF86AudioLowerVolume
	amixer -D pulse set unmute
	amixer sset Master 1%-
	wmiir xwrite /event Notice "Sound: $(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')($(amixer sget Master | awk -F"[][]" '/dB/ { print $6 }'))"
Key XF86AudioRaiseVolume
	amixer -D pulse set unmute
	amixer sset Master 1%+
	wmiir xwrite /event Notice "Sound: $(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')($(amixer sget Master | awk -F"[][]" '/dB/ { print $6 }'))"


KeyGroup Resize windows
Key $MODKEY-Left
	wmiir xwrite /tag/sel/ctl grow sel sel left
Key $MODKEY-Right
	wmiir xwrite /tag/sel/ctl grow sel sel right
Key $MODKEY-Up
	wmiir xwrite /tag/sel/ctl grow sel sel up
Key $MODKEY-Down
	wmiir xwrite /tag/sel/ctl grow sel sel down	
Key $MODKEY-Control-Right
	wmiir xwrite /tag/sel/ctl grow sel sel left -1
Key $MODKEY-Control-Left
	wmiir xwrite /tag/sel/ctl grow sel sel right -1
Key $MODKEY-Control-Down
	wmiir xwrite /tag/sel/ctl grow sel sel up -1
Key $MODKEY-Control-Up
	wmiir xwrite /tag/sel/ctl grow sel sel down -1	
#keys for wmii-helper
KeyGroup Helper
Key Mod3-q
	echo player-pause > $HELPER_FIFO_IN &
Key Mod3-x
	echo player-next > $HELPER_FIFO_IN &
Key Mod3-z
	echo player-loop > $HELPER_FIFO_IN &
Key Mod3-p
	echo wallpaper-next > $HELPER_FIFO_IN &
Key Mod3-s
	{
	MUSIC=`nw /home/userr/.wmii/music-asker.nw`
	echo player-play-file {:path \"$MUSIC\"} > $HELPER_FIFO_IN
	} &

KeyGroup My actions
#ping
Key $MODKEY-i
	eval wmiir setsid 'gnome-terminal --disable-factory -t PING -e "ping 8.8.8.8"' &
#screenshot
Key Print
	eval wmiir setsid "gnome-screenshot" &
Key Mod1-Print
	screenshot &
#lock screen	
Key Mod3-w
	eval wmiir setsid "xscreensaver-command -lock" &
#calculator	
Key $MODKEY-c
	eval wmiir setsid "gnome-calculator" &
#quick launch meni
Key $MODKEY-Tab
	eval wmiir setsid "$(wmii9menu -i subl firefox chromium subl xchat tor-browser screenshot screenshot-area)" &	
#select clear tag
Key $MODKEY-grave
	wmiir xwrite /ctl view $(paste <( wmiir ls /tag | grep -o -E "[0-9]+")  <(seq 100)  | awk '$1!=$2' | head -n1 | awk '{print $NF}')
!


for i in 0 1 2 3 4 5 6 7 8 9; do
wi_events <<!
Key $MODKEY-$i		 # Move to the numbered view
	wmiir xwrite /ctl view "$i"
Key $MODKEY-Shift-$i     # Retag selected client with the numbered tag
	wmiir xwrite /client/sel/ctl tags "$i"
!
done
wi_events -e

# WM Configuration
wmiir write /ctl <<!
	font $WMII_FONT
	focuscolors $WMII_FOCUSCOLORS
	normcolors $WMII_NORMCOLORS
	grabmod $MODKEY
	border 1
!
xsetroot -solid "$WMII_BACKGROUND" &

# Misc
progsfile="$(wmiir namespace)/.proglist"
action status &
wi_proglist $PATH >$progsfile &


# Setup Tag Bar
IFS="$wi_newline"
wmiir rm $(wmiir ls -p /lbar) >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS


wi_tags | while read tag
do
	if [ "$tag" = "$seltag" ]; then
		echo colors "$WMII_FOCUSCOLORS"
		echo label $tag
	else
		echo colors "$WMII_NORMCOLORS"
		echo label $tag
	fi | wmiir create "/lbar/$tag"
done


startup

wi_eventloop

